---

# Upgrade of sqlite database is not possible - just remove it
# rm /var/lib/zabbix/zabbix_proxy.db

- set_fact:
    zabbix_proxy_major_version: "{{ zabbix_proxy_version | regex_replace('^([0-9]+\\.[0-9]+)(.*)$', '\\1') }}"
- set_fact:
    #zabbix_proxy_package: "zabbix-proxy-sqlite3_{{ zabbix_proxy_version }}-1+{{ ansible_distribution_release }}_amd64.deb"
    # Zabbix version >=6: buster -> debian10
    zabbix_proxy_package: "zabbix-proxy-sqlite3_{{ zabbix_proxy_version }}-1+debian{{ ansible_distribution_version }}_amd64.deb"

- name: "Add apt gpg key for repo.zabbix.com"
  copy: src=zabbix-official-repo.gpg dest=/usr/share/keyrings/

# Using apt with a deb downloads the deb everytime we call ansible
- name: Downloading deb
  get_url: 
    url: http://repo.zabbix.com/zabbix/{{ zabbix_proxy_major_version }}/debian/pool/main/z/zabbix/{{ zabbix_proxy_package }}
    dest: /var/cache/apt/archives/{{ zabbix_proxy_package }}

- name: Installing deb
  apt: deb=/var/cache/apt/archives/{{ zabbix_proxy_package }}

- name: Create /etc/zabbix/zabbix_proxy.conf.d/
  file: path=/etc/zabbix/zabbix_proxy.conf.d/ state=directory

- name: Create /var/lib/zabbix/
  file: path=/var/lib/zabbix/ state=directory owner=zabbix group=zabbix mode=750

- name: Create /etc/zabbix/zabbix_proxy.psk (1/2)
  shell: openssl rand -hex 32 > /etc/zabbix/zabbix_proxy.psk
  args:
    creates: /etc/zabbix/zabbix_proxy.psk
  notify: Restart zabbix-proxy

- name: Create /etc/zabbix/zabbix_proxy.psk (2/2)
  file: path=/etc/zabbix/zabbix_proxy.psk owner=root group=zabbix mode=640

- name: Ensure include of /etc/zabbix/zabbix_proxy.conf.d
  lineinfile:
    path: /etc/zabbix/zabbix_proxy.conf
    line: 'Include=/etc/zabbix/zabbix_proxy.conf.d/*.conf'
    insertafter: '^# Include=.*'
  notify: Restart zabbix-proxy

- name: Add zabbix-proxy configuration
  template: src={{ zabbix_proxy_conf }} dest=/etc/zabbix/zabbix_proxy.conf.d/
  notify: Restart zabbix-proxy

# Ensure to use name.service and not only name
- name: Ensure zabbix-proxy startup at system startup
  service: name=zabbix-proxy.service state=started enabled=yes

